<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-Emerson-JRM/blob/main/Actividad_de_semana_5_Python_for_Data_Science_(IBM).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pregunta 1** - What is the result of the following operation: np.array([1,-1])*np.array([1,1])?

In [42]:
import numpy as np
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

**En las Matrices, Arreglos o cualquier operacion aritmética cualquier numero multimplicado por la unidad da como resultado 1**

**Pregunta 2** - What is the result of the following operation: np.dot(np.array([1,-1]),np.array([1,1]))?




In [43]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

****************************************************************************************************************************************************************

# **1D Numpy in Python**

Generacion de Array de una linea, utilizando la libreria Numpy

In [44]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

Puedes Ingresar a cada valor del arreglo usando corchetes, en este caso el arreglo tiene valores de enteros

In [45]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


La version del Numpy

In [46]:
print(np.__version__)

1.21.6


El tipo de arreglo que esta mostrado es un flotante de 64 bits



In [47]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])
b.dtype


dtype('float64')

Asigna el valor de 20 para el segundo elemento del arreglo mostrado

In [48]:
a = np.array([10, 2, 30, 40,50])
a[1]=20
a

array([10, 20, 30, 40, 50])

Podemos asignar un array nuevo con elementos de otro

In [49]:
c = np.array([10, 2, 30, 40,50])
d = c[1:4]
d

array([ 2, 30, 40])

Podemos hacer tambien arreglos de inicio y fin deifnidos en la instruccion

In [50]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


Imprime cualquier elemento del siguiente arreglo
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[1:8:2])

[2 4 6 8]


Para saber el tamaño del arreglo

In [52]:
a = np.array([0, 1, 2, 3, 4])
a
a.size

5

# **Funciones estadisticas**

Para saber el promedio de los datos del arraglo

In [53]:
a = np.array([1, -1, 1, -1])
mean = a.mean()
mean


0.0

para saber la desviacion estandar del arreglo o conjunto de datos

In [54]:
standard_deviation=a.std()
standard_deviation

1.0

Para saber el valor maximo

In [55]:
max_b = b.max()
max_b

213.2

Para saber el valor minimo

In [56]:
min_b = b.min()
min_b

3.1

**Suma el valor maximo y el valor minimo**

In [57]:
c = np.array([-10, 201, 43, 94, 502])
max_c = c.max()
max_c
    
min_c = c.min()
min_c
    
    
Sum = (max_c +min_c)
Sum

492

****************************************************************************************************************************************************************

Pregunta 1 - Numero de filas que contiene este arreglo:
A = np.array([[1,2],[3,4],[5,6],[7,8]])

In [58]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
a.shape

(4,)

Pregunta 2 - Is it possible to perform the following operation?

In [61]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])

B = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.dot(A,B)

ValueError: ignored

****************************************************************************************************************************************************************

# **2D Numpy in Python**

importanfdo librerias

In [62]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

Accessing different elements of a Numpy Array

In [63]:
A[1, 2]


23

Operaciones basicas con los arrays

In [64]:
X = np.array([[1, 0], [0, 1]]) 
X
Y = np.array([[2, 1], [1, 2]]) 
Y
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

Quiz on 2D Numpy Array

Consider the following list a, convert it to Numpy Array.
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [65]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

calcular el numero de arreglo

In [66]:
A.size

12

Access the element on the first row and first and second columns.

In [67]:
A[0][0:2]


array([1, 2])

Perform matrix multiplication with the numpy arrays A and B.

In [68]:
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
X = np.dot(A,B)
X

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])

****************************************************************************************************************************************************************

# **HTTP and Requests**

Requests is a Python Library that allows you to send <code>HTTP/1.1</code> requests easily. We can import the library as follows:


In [69]:
import requests
import os 
from PIL import Image
from IPython.display import IFrame

You can make a <code>GET</code> request via the method <code>get</code> to [www.ibm.com](http://www.ibm.com/?

In [70]:
url='https://www.ibm.com/'
r=requests.get(url)

We have the response object <code>r</code>, this has information about the request, like the status of the request. We can view the status code using the attribute <code>status_code</code>.


In [71]:
r.status_code

200

You can view the request headers:


In [72]:
print(r.request.headers)

{'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Cookie': '_abck=DB43A542C3EA23C0E0F0A01C38AF4656~-1~YAAQyhwhFw0lKqSDAQAANlEhpQhIQjLVJLLBBA34BDrzp33tQTDPPc5USmRQTi5rcYKPT3YC730xxKYC0ctlQ+6gy0IJgxgOGdcUyVy93pCi3SWISGC+mN7Jcuv9zSmyQONoiTvuHV1jTc+oZVgwVfS5rVpxSYilKn19NJIYvlH/auAfPUiH50vuhlgXQzgVrR8nkjr1jI6tRPENITU/oowIzemaiNkAkMc3aVoJ3a3feBJycJiwbdASSrHJwytDqG/xk+DSuVJLsLnXghEagUt+EXcE7cStC+zPkbiPPA7/IYfZGSGtiw8bcPRduJSyoZMHp1t9RjXWlBdaLAidsTXhGwL5+edtq4HqXhpaG+nOKA7z9UQ=~-1~-1~-1; bm_sz=E383E4652EEF0A0C52EC81DE39212685~YAAQyhwhFw4lKqSDAQAANlEhpRHefn3ZGOIngsPCL9tOprXLGzPAMt+dBv9u4F5G0KpaTlEfIllogpjEW8zWomHg0SMKSUv9dwNfnOiPb+7G5iO3sojldPQ2q1TS0M6Az/53wibwTtxxrZDIWljYFJHG1hK5GW0a5P/4cvN9N3n8fXDdl3lAvBYH0Al1BBFjMJTSxdJl0A/NB6JhFZ/GwbD+4xfRG+7r+GkUMcEgDM4YhEVRhPHvsDvGUNKtTflAonZ3EFr39HryyDie4iZIIQsIxKmEd0QYt0pje9xTylg=~3355969~3556147'}


You can view the request body, in the following line, as there is no body for a get request we get a <code>None</code>:


In [73]:
print("request body:", r.request.body)

request body: None


You can view the <code>HTTP</code> response header using the attribute <code>headers</code>. This returns a python dictionary of <code>HTTP</code> response headers.


In [74]:
header=r.headers
print(r.headers)


{'Server': 'Apache', 'Last-Modified': 'Mon, 03 Oct 2022 12:34:16 GMT', 'ETag': '"17fce-5ea208fcd503e-gzip"', 'Accept-Ranges': 'bytes', 'Content-Encoding': 'gzip', 'Content-Type': 'text/html', 'Cache-Control': 'max-age=3600', 'Expires': 'Tue, 04 Oct 2022 23:32:47 GMT', 'X-Akamai-Transformed': '9 21227 0 pmb=mTOE,2', 'Date': 'Tue, 04 Oct 2022 22:32:47 GMT', 'Content-Length': '21404', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'x-content-type-options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': 'upgrade-insecure-requests', 'Strict-Transport-Security': 'max-age=31536000'}


We can obtain the date the request was sent using the key <code>Date</code>


In [75]:
header['date']

'Tue, 04 Oct 2022 22:32:47 GMT'

<code>Content-Type</code> indicates the type of data:

In [78]:
header['Content-Type']

'text/html'

You can also check the encoding:

In [77]:
 r.encoding

'ISO-8859-1'

As the Content-Type is text/html we can use the attribute text to display the HTML in the body. We can review the first 100 characters:

In [60]:
r.text[0:100]

'<!DOCTYPE html><html lang="en-US"><head><meta name="viewport" content="width=device-width"/><meta ch'

****************************************************************************************************************************************************************

# **Simple APIs**

To start using the API you can install the `randomuser` library running the `pip install` command.


In [79]:
!pip install randomuser

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5084 sha256=f31177956c2813af6093265ae6f783fd027d91905a011a8d498deecb82938bd1
  Stored in directory: /root/.cache/pip/wheels/21/10/7b/c13bc3e24a3c1000a34554802ad8aa0ff27df56366998a0473
Successfully built randomuser


Then, we will load the necessary libraries.


In [81]:
from randomuser import RandomUser
import pandas as pd

First, we will create a random user object, r.


In [82]:
r = RandomUser()

Then, using `generate_users()` function, we get a list of random 10 users.

In [83]:
some_list = r.generate_users(10)
some_list

Let's say we only need 10 users with full names and their email addresses. We can write a "for-loop" to print these 10 users.


In [84]:
for user in some_list:
    print (user.get_full_name()," ",user.get_email())

Ronald Fleming   ronald.fleming@example.com
Sofia Herrera   sofia.herrera@example.com
Henry Evans   henry.evans@example.com
Matas Warsame   matas.warsame@example.com
Dino Holzner   dino.holzner@example.com
Leah Lucas   leah.lucas@example.com
Emilia Laitinen   emilia.laitinen@example.com
Salvador Santos   salvador.santos@example.com
Harper Brar   harper.brar@example.com
Kornelius Håpnes   kornelius.hapnes@example.com


****************************************************************************************************************************************************************

# Review Questions

What is the result of the following lines of code:

In [85]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

What is the result of the following lines of code:

In [86]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

What is the result of the following lines of code:

In [87]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])