<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-Emerson-JRM/blob/main/Actividad_de_semana_5_Python_for_Data_Science_(IBM).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pregunta 1** - What is the result of the following operation: np.array([1,-1])*np.array([1,1])?

In [2]:
import numpy as np
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

**En las Matrices, Arreglos o cualquier operacion aritmética cualquier numero multimplicado por la unidad da como resultado 1**

**Pregunta 2** - What is the result of the following operation: np.dot(np.array([1,-1]),np.array([1,1]))?




In [5]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

****************************************************************************************************************************************************************

# **1D Numpy in Python**

Generacion de Array de una linea, utilizando la libreria Numpy

In [4]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

Puedes Ingresar a cada valor del arreglo usando corchetes, en este caso el arreglo tiene valores de enteros

In [6]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


La version del Numpy

In [7]:
print(np.__version__)

1.21.6


El tipo de arreglo que esta mostrado es un flotante de 64 bits



In [8]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])
b.dtype


dtype('float64')

Asigna el valor de 20 para el segundo elemento del arreglo mostrado

In [9]:
a = np.array([10, 2, 30, 40,50])
a[1]=20
a

array([10, 20, 30, 40, 50])

Podemos asignar un array nuevo con elementos de otro

In [12]:
c = np.array([10, 2, 30, 40,50])
d = c[1:4]
d

array([ 2, 30, 40])

Podemos hacer tambien arreglos de inicio y fin deifnidos en la instruccion

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


Imprime cualquier elemento del siguiente arreglo
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[1:8:2])

[2 4 6 8]


Para saber el tamaño del arreglo

In [15]:
a = np.array([0, 1, 2, 3, 4])
a
a.size

5

# **Funciones estadisticas**

Para saber el promedio de los datos del arraglo

In [16]:
a = np.array([1, -1, 1, -1])
mean = a.mean()
mean


0.0

para saber la desviacion estandar del arreglo o conjunto de datos

In [17]:
standard_deviation=a.std()
standard_deviation

1.0

Para saber el valor maximo

In [18]:
max_b = b.max()
max_b

213.2

Para saber el valor minimo

In [19]:
min_b = b.min()
min_b

3.1

**Suma el valor maximo y el valor minimo**

In [20]:
c = np.array([-10, 201, 43, 94, 502])
max_c = c.max()
max_c
    
min_c = c.min()
min_c
    
    
Sum = (max_c +min_c)
Sum

492

****************************************************************************************************************************************************************

Pregunta 1 - Numero de filas que contiene este arreglo:
A = np.array([[1,2],[3,4],[5,6],[7,8]])

In [22]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
a.shape

(4,)

Pregunta 2 - Is it possible to perform the following operation?

In [23]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])

B = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.dot(A,B)

ValueError: ignored

****************************************************************************************************************************************************************

# **2D Numpy in Python**

importanfdo librerias

In [24]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

Accessing different elements of a Numpy Array

In [25]:
A[1, 2]


23

Operaciones basicas con los arrays

In [27]:
X = np.array([[1, 0], [0, 1]]) 
X
Y = np.array([[2, 1], [1, 2]]) 
Y
Z = X + Y
Z

array([[3, 1],
       [1, 3]])